### ISSUE TITLE
getting errors while running ./startFabric.sh up

### ISSUE THREAD

**Issue by firewind25** [arefin97/Medicine_Supply_Chain#8]
I've downloaded the repo installed all pre requisties but still i get this error when i ran `./startFabric.sh up` :-

**The chaincode language up is not supported by this script
Supported chaincode languages are: go, javascript, and typescript**

so i executed `./startFabric.sh` and `./startFabric.sh go` and i got this msg:-

**./startFabric.sh: ./byfn.sh: /bin/bash^M: bad interpreter: No such file or directory**

I don't know what's the reason cause I've installed all those lang mentioned there.

**Comment by arefin97** [comment]
It is not the matter of installing all languages.
You have to set path of golang, fabric bin etc properly so that your system find these out.
And you will face another problem here - Local fabric binaries and docker images will not match as I develop it some time ago.
You can download docker-compose v1.24 to match with fabric version or work all new(updated fabric image and docker image).

**Comment by chaitanyamet25** [comment]
![Screenshot from 2021-05-04 18-25-31](https://user-images.githubusercontent.com/40482752/117006613-48ef8d80-ad06-11eb-888f-d8a6d3288ee9.png)

I'm getting this error now ,
error getting chaincode deployment spec for medicine

**Comment by arefin97** [comment]
If gopath is properly set up,
then try downloading the shim package to the GOPATH
$go get github.com/hyperledger/fabric-chaincode-go/shim

then again execute the script.

**Comment by chaitanyamet25** [comment]
I've seen in my GOPATH that there is already a shim file in it. my GOPATH is set to Home/myusername/go dir is this okay right?

**Comment by chaitanyamet25** [comment]
i was getting an error after executing this cmd $go get git.../shim

package math/bits: unrecognized import path "math/bits" (import path does not begin with hostname)
package context: unrecognized import path "context" (import path does not begin with hostname)
package net/http/httptrace: unrecognized import path "net/http/httptrace" (import path does not begin with hostname)

**Comment by arefin97** [comment]
I have updated some things.
re-download or reclone it.
go to $cd /Medicine_Supply_Chain/Medi_Chain/chaincode/medicine/go
and run $GO111MODULE=on go mod vendor

If successfully installed chaincode, goto javascript folder and run $npm
install or npm update
and some instructions I have provided you earlier.

Or go through readme.md where I have provided some instructions now.

**Comment by firewind25** [comment]
I've logged into admin page and added producer, but I don't see any option for producer adding medicines how can producer at medicine.

**Comment by arefin97** [comment]
Then login as producer to add medicine.

**Comment by arefin97** [comment]
Actually, you have to signup this producer. It works in this way that only
those entities can be registered as producer who are added by admin already.
Similar for dealer. But no need for endusers.

**Comment by firewind25** [comment]
How to login as producer cause while adding it no password is asked but while signing in password is required

**Comment by arefin97** [comment]
I think I made it clear in my previous reply. Okay, let's have an example.
Suppose Mr x want to be a producer. If he wan't to sign up as producer,
system will show you can't be a producer.
If admin add Mr x add as a producer, then using this ID Mr x can be
registered as producer.

**Comment by firewind25** [comment]
Oh... yes, I got it, first register then sign up. Ok.
Thank you👍
